# Generated by Django 5.1.7 on 2025-03-26 08:45

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(default='About Us', max_length=100, verbose_name='العنوان بالإنجليزية')),
                ('title_ar', models.CharField(default='نبذة عنا', max_length=100, verbose_name='العنوان بالعربية')),
            ],
            options={
                'verbose_name': 'نبذة عنا ',
                'verbose_name_plural': 'نبذة عنا ',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255, verbose_name='الاسم بالإنجليزية')),
                ('name_ar', models.CharField(max_length=255, verbose_name='الاسم بالعربية')),
                ('description_en', models.TextField(blank=True, verbose_name='الوصف بالإنجليزية')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف بالعربية')),
                ('image', models.ImageField(null=True, upload_to='categories/', verbose_name='الصورة')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'الفئات',
                'verbose_name_plural': 'الفئات',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=255, verbose_name='رقم الهاتف')),
                ('subject', models.CharField(max_length=255, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
            ],
            options={
                'verbose_name': 'تواصل معنا',
                'verbose_name_plural': 'تواصل معنا',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200, verbose_name='العنوان بالإنجليزية')),
                ('title_ar', models.CharField(max_length=200, verbose_name='العنوان بالعربية')),
                ('image', models.ImageField(blank=True, null=True, upload_to='documentsImages/', verbose_name='الصورة')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'المستندات',
                'verbose_name_plural': 'المستندات',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_name_ar', models.CharField(max_length=255, verbose_name='اسم الخدمة بالعربية')),
                ('services_name_en', models.CharField(max_length=255, verbose_name='اسم الخدمة بالإنجليزية')),
                ('description_ar', models.TextField(verbose_name='الوصف بالعربية')),
                ('description_en', models.TextField(verbose_name='الوصف بالإنجليزية')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='الصورة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'الخدمات',
                'verbose_name_plural': 'الخدمات',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='العنوان بالإنجليزية')),
                ('title_ar', models.CharField(blank=True, max_length=200, null=True, verbose_name='العنوان بالعربية')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='الوصف بالإنجليزية')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='الوصف بالعربية')),
                ('image', models.ImageField(upload_to='sliders/', verbose_name='الصورة')),
                ('link', models.URLField(blank=True, verbose_name='رابط إضافي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'الصور في الصفحة الرئيسية',
                'verbose_name_plural': 'الصور في الصفحة الرئيسية',
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/', verbose_name='الملف')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.document', verbose_name='المستند')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255, verbose_name='الاسم بالإنجليزية')),
                ('name_ar', models.CharField(max_length=255, verbose_name='الاسم بالعربية')),
                ('description_en', models.TextField(verbose_name='الوصف بالإنجليزية')),
                ('description_ar', models.TextField(verbose_name='الوصف بالعربية')),
                ('image', models.ImageField(upload_to='products/', verbose_name='الصورة')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإضافة')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.category', verbose_name='الفئة')),
                ('related_products', models.ManyToManyField(blank=True, to='api.product', verbose_name='منتجات قد تعجبك')),
            ],
            options={
                'verbose_name': 'المنتجات',
                'verbose_name_plural': 'المنتجات',
            },
        ),
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='product_docs/', verbose_name='الملف')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.product', verbose_name='المنتج')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255, verbose_name='العنوان بالإنجليزية')),
                ('title_ar', models.CharField(max_length=255, verbose_name='العنوان بالعربية')),
                ('description_en', django_ckeditor_5.fields.CKEditor5Field(verbose_name='الوصف بالإنجليزية')),
                ('description_ar', django_ckeditor_5.fields.CKEditor5Field(verbose_name='الوصف بالعربية')),
                ('image', models.ImageField(upload_to='solutions/', verbose_name='الصورة')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإضافة')),
                ('related_products', models.ManyToManyField(blank=True, to='api.product', verbose_name='المواد المستخدمة')),
            ],
            options={
                'verbose_name': 'الحلول',
                'verbose_name_plural': 'الحلول',
            },
        ),
        migrations.CreateModel(
            name='AboutUsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.PositiveSmallIntegerField(unique=True, verbose_name='رقم القسم')),
                ('text_en', models.TextField(verbose_name='النص بالإنجليزية')),
                ('text_ar', models.TextField(verbose_name='النص بالعربية')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_us/', verbose_name='الصورة')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='api.aboutus', verbose_name='نبذة عنا')),
            ],
            options={
                'verbose_name': 'نبذة عنا ',
                'verbose_name_plural': 'نبذة عنا ',
                'ordering': ['section_number'],
                'unique_together': {('about_us', 'section_number')},
            },
        ),
    ]
