# Generated by Django 5.1.7 on 2025-03-10 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_category_options_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'تواصل معنا', 'verbose_name_plural': 'تواصل معنا'},
        ),
    ]
